# Generated by Django 5.0.2 on 2024-04-04 16:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completeStep', models.PositiveIntegerField()),
                ('traveledDistance', models.FloatField()),
                ('kalory', models.PositiveIntegerField()),
                ('traveledTime', models.TimeField()),
                ('dayDate', models.DateField()),
                ('dailyExercise', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
