# Generated by Django 5.0.2 on 2024-04-04 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinfo',
            name='dailyExercise',
            field=models.BooleanField(default=False),
        ),
    ]
