# Generated by Django 5.0.2 on 2024-04-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_alter_dailyinfo_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyinfo',
            old_name='kalory',
            new_name='calory',
        ),
    ]
