# Generated by Django 5.0.2 on 2024-07-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_rename_kalory_dailyinfo_calory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyinfo',
            name='dayDate',
            field=models.DateField(auto_now_add=True),
        ),
    ]
