# Generated by Django 5.0.2 on 2024-07-12 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_alter_dailyinfo_daydate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyinfo',
            name='is_firstTime',
            field=models.BooleanField(default=True),
        ),
    ]
