# Generated by Django 5.0.2 on 2024-07-12 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_dailyinfo_is_firsttime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyinfo',
            name='is_firstTime',
        ),
    ]
