# Generated by Django 5.0.2 on 2024-02-23 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_city_userprofile_provinces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(default='media/default.jpg', upload_to='media/UserProfile'),
        ),
    ]
