# Generated by Django 5.0.2 on 2024-02-23 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_userprofile_profileimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImage',
            field=models.ImageField(default='default.jpg', upload_to='media/UserProfile'),
        ),
    ]
