# Generated by Django 5.0.2 on 2024-03-07 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userprofile_profileimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SportPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sportPlaces',
            field=models.ManyToManyField(to='account.sportplace'),
        ),
        migrations.CreateModel(
            name='UserHealth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('healthProblem', models.CharField(blank=True, choices=[('بله ، مشکلی دارم', 'بله ، مشکلی دارم'), ('نه ، ندارم', 'نه ، ندارم')], max_length=100, null=True)),
                ('weeklyGoal', models.CharField(choices=[('1 بار در هفته', '1 بار در هفته'), ('2 بار در هفته', '2 بار در هفته'), ('3 بار در هفته', '3 بار در هفته'), ('بیش از 3 بار در هفته', 'بیش از 3 بار در هفته')], max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
