# Generated by Django 5.0.2 on 2024-03-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_sportplace_userprofile_sportplaces_userhealth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userhealth',
            name='healthProblemContent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userhealth',
            name='healthProblem',
            field=models.CharField(choices=[('بله ، مشکلی دارم', 'بله ، مشکلی دارم'), ('نه ، ندارم', 'نه ، ندارم')], max_length=100),
        ),
    ]
