# Generated by Django 5.0.2 on 2024-03-17 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_userprofile_age_alter_userprofile_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='purpesSteps',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
