# Generated by Django 5.0.2 on 2024-03-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userprofile_purpessteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='purpesSteps',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
