# Generated by Django 5.0.2 on 2024-03-31 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userprofile_purpessteps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
