# Generated by Django 5.0.2 on 2024-03-31 20:24

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_userprofile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='referrer_code',
            field=models.CharField(default=account.models.generate_referrer_code, max_length=6),
        ),
    ]
