# Generated by Django 5.0.2 on 2024-04-03 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_userprofile_referrer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userProblem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='weeklyGoal',
            field=models.CharField(choices=[('1 بار در هفته', '1 بار در هفته'), ('2 بار در هفته', '2 بار در هفته'), ('3 بار در هفته', '3 بار در هفته'), ('بیش از 3 بار در هفته', 'بیش از 3 بار در هفته')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='boostUser',
            field=models.ManyToManyField(to='account.boostuser'),
        ),
        migrations.DeleteModel(
            name='UserHealth',
        ),
    ]
