# Generated by Django 5.0.2 on 2024-04-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_boostuser_userprofile_userproblem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='weeklyGoal',
            field=models.CharField(choices=[('1', '1 بار در هفته'), ('2', '2 بار در هفته'), ('3', '3 بار در هفته'), ('more', 'بیش از 3 بار در هفته')], max_length=100, null=True),
        ),
    ]
