# Generated by Django 5.0.2 on 2024-04-06 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_userprofile_weeklygoal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='purpesSteps',
            new_name='purposeSteps',
        ),
    ]
