# Generated by Django 5.0.2 on 2024-04-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_rename_purpessteps_userprofile_purposesteps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='purposeSteps',
            field=models.PositiveIntegerField(default=5000, null=True),
        ),
    ]
