# Generated by Django 5.0.2 on 2024-08-31 00:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_alter_userprofile_purposesteps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='related_referrer',
            field=models.ManyToManyField(blank=True, related_name='related_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
