# Generated by Django 5.0.2 on 2024-09-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0019_userprofile_related_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='levelXp',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
