# Generated by Django 5.0.2 on 2024-09-14 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactUs_db',
        ),
    ]
