# Generated by Django 5.0.2 on 2024-09-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepsupport',
            name='receiver_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
