# Generated by Django 5.0.2 on 2024-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0002_alter_stepsupport_receiver_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stepsupport',
            name='receiver_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
