# Generated by Django 5.0.2 on 2024-09-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0003_alter_stepsupport_receiver_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
            ],
        ),
    ]
